version: '3.8'

services:
    nginx:
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
          - "8500:80"
          - "9081:8080"
        networks:
          - a11y-net
          - cloudflare

# Add load balances here
# Axe CLI Endpoint
    scan-axe-1:
      image: equalifyapp/integration-axe:latest
      environment:
        APP_PORT: 8086
        http_proxy: http://localhost:18888
        https_proxy: http://localhost:18888
        FLASK_APP: axe.py
      networks:
        - a11y-net

    scan-axe-2:
      image: equalifyapp/integration-axe:latest
      environment:
        APP_PORT: 8086
        http_proxy: http://localhost:18888
        https_proxy: http://localhost:18888
        FLASK_APP: axe.py
      networks:
        - a11y-net

    scan-axe-3:
      image: equalifyapp/integration-axe:latest
      environment:
        APP_PORT: 8086
        http_proxy: http://localhost:18888
        https_proxy: http://localhost:18888
        FLASK_APP: axe.py
      networks:
        - a11y-net

    scan-axe-4:
      image: equalifyapp/integration-axe:latest
      environment:
        APP_PORT: 8086
        http_proxy: http://localhost:18888
        https_proxy: http://localhost:18888
        FLASK_APP: axe.py
      networks:
        - a11y-net

    scan-axe-5:
      image: equalifyapp/integration-axe:latest
      environment:
        APP_PORT: 8086
        http_proxy: http://localhost:18888
        https_proxy: http://localhost:18888
        FLASK_APP: axe.py
      networks:
        - a11y-net


# Tech Check Endpoint
# TODO need to finish building this...
    scan-tech-1:
        image: ghcr.io/hunter-io/wappalyzer-api:3.6
        networks:
          - a11y-net

    scan-tech-2:
        image: ghcr.io/hunter-io/wappalyzer-api:3.6
        networks:
          - a11y-net


networks:
  a11y-net:
  cloudflare:
    external: true
