version: '3.8'

services:

# Workers
    scan-axe:
        image: equalifyapp/integration-axe:latest
        environment:
            - APP_PORT=8083
            - RABBIT_USERNAME=worker_axe
            - RABBIT_PASSWORD=drop_the_axe
            - RABBIT_HOST=rabbit
            - RABBIT_VHOST=gova11y
            - USE_PROXY=true
            - PROXY_HTTP=a11yproxy:8888
            - PROXY_HTTPS=a11yproxy:8888
            - LOG_LEVEL
        networks:
            - gova11y-int
        depends_on:
            - rabbit
            - a11yproxy
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure

    scan-uppies:
        image: equalifyapp/integration-uppies:latest
        environment:
            - APP_PORT=8083
            - RABBIT_USERNAME=worker_uppies
            - RABBIT_PASSWORD=pass_the_uppies_please
            - RABBIT_HOST=rabbit
            - RABBIT_VHOST=gova11y
            - USE_PROXY=true
            - PROXY_HTTP=a11yproxy:8888
            - PROXY_HTTPS=a11yproxy:8888
            - LOG_LEVEL
        networks:
            - gova11y-int
        depends_on:
            - rabbit
            - a11yproxy
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure



# RabbitMQ Service
    rabbit:
        image: equalifyapp/a11y-rabbit:latest
        ports:
            - "4369:4369/tcp"
            - "5672:5672/tcp"
            - "15672:15672/tcp"
        networks:
            - gova11y-int
        deploy:
          restart_policy:
              condition: on-failure

# Matrix
    matrix:
        image: equalifyapp/a11ymatrix:latest
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USER=a11ydata
            - DB_PASSWORD=a11yAllTheThings!
            - DB_NAME=a11ydata
            - LOG_LEVEL
            - APP_PORT=8087
        ports:
            - "8087:8087/tcp"
        networks:
            - gova11y-int
            - gova11y-mid
        depends_on:
            - rabbit
            - postgres
        deploy:
            restart_policy:
                condition: on-failure

# Rabbit Hole - Insert values to Postgres
    rabbit-hole:
        image: equalifyapp/rabbit-hole:latest
        environment:
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_USER=a11ydata
        - DB_PASSWORD=a11yAllTheThings!
        - DB_NAME=a11ydata
        - LOG_LEVEL
        - APP_PORT=8084
        ports:
            - "8084:8084"
        networks:
            - gova11y-int
            - gova11y-mid
        depends_on:
            - rabbit
            - postgres
        deploy:
            restart_policy:
                condition: on-failure


# Grafana
    a11yfana:
        image: equalifyapp/a11yfana:latest
        ports:
            - "3000:3000"
        networks:
            - gova11y-mid
            - gova11y_ext
        depends_on:
            - postgres
        volumes:
            - a11yfana_data:/var/lib/grafana

# Postgres
    postgres:
        image: equalifyapp/database:latest
        environment:
            - POSTGRES_DB=a11ydata
            - POSTGRES_USER=a11ydata
            - POSTGRES_PASSWORD=a11yAllTheThings!
            - POSTGRES_PORT=5432
        ports:
            - "5432:5432"
        networks:
            - gova11y-mid
        volumes:
            - a11ygres_data:/var/lib/postgresql/data

# Proxy Server
    a11yproxy:
        image: qmcgaw/gluetun:latest
        cap_add:
            - NET_ADMIN
        environment:
            - VPN_SERVICE_PROVIDER=mullvad
            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY
            - WIREGUARD_ADDRESSES=10.65.90.193/32
            - SERVER_COUNTRIES=USA
            # HTTP Proxy: https://github.com/qdm12/gluetun/wiki/HTTP-proxy-options
            - HTTPPROXY=on
            - HTTPPROXY_LOG=on
            - HTTPPROXY_LISTENING_ADDRESS=:8888
            # DNS: https://github.com/qdm12/gluetun/wiki/DNS-options
            - DNS_ADDRESS=127.0.0.1
            - DOT_PRIVATE_ADDRESS=172.172.172.172
            - BLOCK_MALICIOUS=off
            - DOT_CACHING=on
            - DOT=on
            # Other Options: https://github.com/qdm12/gluetun/wiki/Other-options
            - TZ=AMERICA/NEW_YORK
            # Firewall: https://github.com/qdm12/gluetun/wiki/Firewall-options
            - FIREWALL_DEBUG=on
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
        networks:
            - gova11y-int


networks:
    gova11y-int:
    gova11y-mid:
    gova11y-ext:

volumes:
    a11ygres_data:
    a11yfana_data:
