version: '3.8'

services:

# Workers
    scan-axe:
        image: equalifyapp/integration-axe:latest
        environment:
            - APP_PORT=8083
            - RABBIT_USERNAME=worker_axe
            - RABBIT_PASSWORD=drop_the_axe
            - RABBIT_HOST=rabbit
            - RABBIT_VHOST=gova11y
            - USE_PROXY=true
            - PROXY_HTTP=nginx:8888
            - PROXY_HTTPS=nginx:8888
            - LOG_LEVEL
        networks:
            - gova11y-int
        depends_on:
            - rabbit
            - a11yproxy
        deploy:
            replicas: 5
            restart_policy:
                condition: on-failure

    scan-uppies:
        image: equalifyapp/integration-uppies:latest
        environment:
            - APP_PORT=8083
            - RABBIT_USERNAME=worker_uppies
            - RABBIT_PASSWORD=pass_the_uppies_please
            - RABBIT_HOST=rabbit
            - RABBIT_VHOST=gova11y
            - USE_PROXY=true
            - PROXY_HTTP=nginx:8888
            - PROXY_HTTPS=nginx:8888
            - LOG_LEVEL
        networks:
            - gova11y-int
        depends_on:
            - rabbit
            - a11yproxy
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure



# RabbitMQ Service
    rabbit:
        image: equalifyapp/a11y-rabbit:latest
        ports:
            - "4369:4369/tcp"
            - "5672:5672/tcp"
            - "15672:15672/tcp"
        networks:
            - gova11y-int
        deploy:
          restart_policy:
              condition: on-failure

# Matrix

    matrix:
        image: equalifyapp/a11ymatrix:latest
        ports:
            - "8087:8087/tcp"
        networks:
            - gova11y-int
            - gova11y-ext
        depends_on:
            - rabbit
        deploy:
            restart_policy:
                condition: on-failure

# Rabbit Hole - Insert values to Postgres

    rabbit-hole:
        image: equalifyapp/rabbit-hole:latest
        ports:
            - "8084:8084"
        networks:
            - gova11y-int
            - gova11y-ext
        depends_on:
            - rabbit
        deploy:
            restart_policy:
                condition: on-failure


# DNS & Proxy Load Balance
    nginx:
        image: equalifyapp/nginx-proxy:latest
        ports:
            - "8888:8888"
        networks:
            - gova11y-int
            - gova11y-proxy
        deploy:
            replicas: 1
            restart_policy:
                condition: unless-stopped


    a11yproxy-1:
        image: qmcgaw/gluetun:latest
        cap_add:
            - NET_ADMIN
        environment:
            - VPN_SERVICE_PROVIDER=mullvad
            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY
            - WIREGUARD_ADDRESSES=10.65.90.193/32
            - SERVER_COUNTRIES=USA
            # HTTP Proxy: https://github.com/qdm12/gluetun/wiki/HTTP-proxy-options
            - HTTPPROXY=on
            - HTTPPROXY_LOG=on
            - HTTPPROXY_LISTENING_ADDRESS=:8888
            # DNS: https://github.com/qdm12/gluetun/wiki/DNS-options
            - DNS_ADDRESS=192.168.1.56
            - DOT_PRIVATE_ADDRESS=172.172.172.172
            - BLOCK_MALICIOUS=off
            - DOT_CACHING=off
            - DOT=off
            # Other Options: https://github.com/qdm12/gluetun/wiki/Other-options
            - TZ=AMERICA/NEW_YORK
            # Firewall: https://github.com/qdm12/gluetun/wiki/Firewall-options
            - FIREWALL_DEBUG=on
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - gova11y-proxy

    a11yproxy-2:
        image: qmcgaw/gluetun:latest
        cap_add:
            - NET_ADMIN
        environment:
            - VPN_SERVICE_PROVIDER=mullvad
            - VPN_TYPE=wireguard
            - WIREGUARD_PRIVATE_KEY
            - WIREGUARD_ADDRESSES=10.65.90.193/32
            - SERVER_COUNTRIES=USA
            # HTTP Proxy: https://github.com/qdm12/gluetun/wiki/HTTP-proxy-options
            - HTTPPROXY=on
            - HTTPPROXY_LOG=on
            - HTTPPROXY_LISTENING_ADDRESS=:8888
            # DNS: https://github.com/qdm12/gluetun/wiki/DNS-options
            - DNS_ADDRESS=192.168.1.56
            - DOT_PRIVATE_ADDRESS=172.172.172.172
            - BLOCK_MALICIOUS=off
            - DOT_CACHING=off
            - DOT=off
            # Other Options: https://github.com/qdm12/gluetun/wiki/Other-options
            - TZ=AMERICA/NEW_YORK
            # Firewall: https://github.com/qdm12/gluetun/wiki/Firewall-options
            - FIREWALL_DEBUG=on
        deploy:
            restart_policy:
                condition: on-failure
        networks:
            - gova11y-proxy

    a11yproxy-3:
            image: qmcgaw/gluetun:latest
            cap_add:
                - NET_ADMIN
            environment:
                - VPN_SERVICE_PROVIDER=mullvad
                - VPN_TYPE=wireguard
                - WIREGUARD_PRIVATE_KEY
                - WIREGUARD_ADDRESSES=10.65.90.193/32
                - SERVER_COUNTRIES=USA
                # HTTP Proxy: https://github.com/qdm12/gluetun/wiki/HTTP-proxy-options
                - HTTPPROXY=on
                - HTTPPROXY_LOG=on
                - HTTPPROXY_LISTENING_ADDRESS=:8888
                # DNS: https://github.com/qdm12/gluetun/wiki/DNS-options
                - DNS_ADDRESS=192.168.1.56
                - DOT_PRIVATE_ADDRESS=172.172.172.172
                - BLOCK_MALICIOUS=off
                - DOT_CACHING=off
                - DOT=off
                # Other Options: https://github.com/qdm12/gluetun/wiki/Other-options
                - TZ=AMERICA/NEW_YORK
                # Firewall: https://github.com/qdm12/gluetun/wiki/Firewall-options
                - FIREWALL_DEBUG=on
            deploy:
                restart_policy:
                    condition: on-failure
            networks:
                - gova11y-proxy

networks:
    gova11y-int:
    gova11y-ext:
    gova11y-proxy: